//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfABMCExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artesania_Categoria
    {
        public int Id_Artesania_Categoria { get; set; }
        public int Artesania_Id { get; set; }
        public int Categoria_Id { get; set; }
    
        public virtual Artesania Artesania { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
