//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfABMCExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artesania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artesania()
        {
            this.Artesania_Categoria = new HashSet<Artesania_Categoria>();
        }
    
        public int Id_Artesania { get; set; }
        public string Descripcion { get; set; }
        public int Material_Id { get; set; }
        public string Procedencia { get; set; }
        public string PathImagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artesania_Categoria> Artesania_Categoria { get; set; }
        public virtual Material Material { get; set; }
    }
}
